<?php

use Illuminate\Database\Seeder;

class PropertiesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('properties')->delete();

        \DB::table('properties')->insert(array (
            0 =>
                array (
                    'id' => 1,
                    'agent' => 16,
                    'category' => 'Kos',
                    'isSell' => 0,
                    'isRent' => 0,
                    'name' => 'GRIYA ELIVA',
                    'bath_room' => 2,
                    'bed_room' => 8,
                    'stories' => 2,
                    'land_area' => 10,
                    'building_area' => 50,
                    'location' => NULL,
                    'address' => 'Jl Sunan Kalijaga',
                    'description' => 'hahaha',
                    'image' => 'storage/image/guideline/15934565970.jpeg,storage/image/guideline/15934565971.jpeg,storage/image/guideline/15934565972.jpeg,storage/image/guideline/15934565973.jpeg,storage/image/guideline/15934565974.jpeg,storage/image/guideline/15934565975.jpeg,storage/image/guideline/15934565976.jpeg',
                    'main_image' => 'storage/image/guideline/15934565970.jpeg',
                    'created_at' => '2020-06-29 18:49:57',
                    'updated_at' => '2020-06-29 18:49:57',
                ),
            1 =>
                array (
                    'id' => 2,
                    'agent' => 5,
                    'category' => 'Kos',
                    'isSell' => 0,
                    'isRent' => 0,
                    'name' => 'Kos Zahira',
                    'bath_room' => 2,
                    'bed_room' => 8,
                    'stories' => 2,
                    'land_area' => 10,
                    'building_area' => 45,
                    'location' => NULL,
                    'address' => 'Jl sunan Kalijaga Dalam',
                    'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                    'image' => 'storage/image/guideline/15934568440.jpeg,storage/image/guideline/15934568441.jpeg,storage/image/guideline/15934568442.jpeg,storage/image/guideline/15934568443.jpeg,storage/image/guideline/15934568444.jpeg,storage/image/guideline/15934568445.jpeg',
                    'main_image' => 'storage/image/guideline/15934568440.jpeg',
                    'created_at' => '2020-06-29 18:54:04',
                    'updated_at' => '2020-06-29 18:54:04',
                ),
            2 =>
                array (
                    'id' => 3,
                    'agent' => 4,
                    'category' => 'Rumah',
                    'isSell' => 0,
                    'isRent' => 0,
                    'name' => 'Boegenvil',
                    'bath_room' => 2,
                    'bed_room' => 2,
                    'stories' => 1,
                    'land_area' => 10,
                    'building_area' => 50,
                    'location' => NULL,
                    'address' => 'Jl Diponegoro',
                    'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                    'image' => 'storage/image/guideline/15934569110.jpeg,storage/image/guideline/15934569111.jpeg,storage/image/guideline/15934569112.webp,storage/image/guideline/15934569123.jpeg',
                    'main_image' => 'storage/image/guideline/15934569110.jpeg',
                    'created_at' => '2020-06-29 18:55:12',
                    'updated_at' => '2020-06-29 18:55:12',
                ),
            3 =>
                array (
                    'id' => 4,
                    'agent' => 5,
                    'category' => 'Kontrakan',
                    'isSell' => 0,
                    'isRent' => 0,
                    'name' => 'Geneng Permai',
                    'bath_room' => 16,
                    'bed_room' => 4,
                    'stories' => 1,
                    'land_area' => 10,
                    'building_area' => 35,
                    'location' => NULL,
                    'address' => 'Jl Suhat',
                    'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                    'image' => 'storage/image/guideline/15934570340.jpeg,storage/image/guideline/15934570341.jpeg,storage/image/guideline/15934570342.jpeg,storage/image/guideline/15934570343.jpeg,storage/image/guideline/15934570344.jpeg,storage/image/guideline/15934570345.jpeg',
                    'main_image' => 'storage/image/guideline/15934570340.jpeg',
                    'created_at' => '2020-06-29 18:57:14',
                    'updated_at' => '2020-06-29 18:57:14',
                ),
            4 =>
                array (
                    'id' => 5,
                    'agent' => 5,
                    'category' => 'Kontrakan',
                    'isSell' => 0,
                    'isRent' => 0,
                    'name' => 'Green Pramuka City',
                    'bath_room' => 1,
                    'bed_room' => 2,
                    'stories' => 1,
                    'land_area' => 5,
                    'building_area' => 35,
                    'location' => NULL,
                    'address' => 'Jl Habibie',
                    'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                    'image' => 'storage/image/guideline/15934571380.jpeg,storage/image/guideline/15934571381.jpeg,storage/image/guideline/15934571382.jpeg,storage/image/guideline/15934571383.jpeg',
                    'main_image' => 'storage/image/guideline/15934571380.jpeg',
                    'created_at' => '2020-06-29 18:58:58',
                    'updated_at' => '2020-06-29 18:58:58',
                ),
            5 =>
                array (
                    'id' => 6,
                    'agent' => 5,
                    'category' => 'Kos',
                    'isSell' => 0,
                    'isRent' => 0,
                    'name' => 'Kos Kuning',
                    'bath_room' => 9,
                    'bed_room' => 18,
                    'stories' => 3,
                    'land_area' => 10,
                    'building_area' => 60,
                    'location' => NULL,
                    'address' => 'Jl Kamboja',
                    'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                    'image' => 'storage/image/guideline/15934572170.jpeg,storage/image/guideline/15934572171.jpeg,storage/image/guideline/15934572172.jpeg,storage/image/guideline/15934572173.jpeg,storage/image/guideline/15934572174.jpeg,storage/image/guideline/15934572175.jpeg,storage/image/guideline/15934572176.jpeg',
                    'main_image' => 'storage/image/guideline/15934572170.jpeg',
                    'created_at' => '2020-06-29 19:00:17',
                    'updated_at' => '2020-06-29 19:00:17',
                ),
            6 =>
                array (
                    'id' => 7,
                    'agent' => 4,
                    'category' => 'Rumah',
                    'isSell' => 0,
                    'isRent' => 0,
                    'name' => 'Orchid Green Park , Rumah Siap Huni Tanpa DP',
                    'bath_room' => 2,
                    'bed_room' => 4,
                    'stories' => 2,
                    'land_area' => 10,
                    'building_area' => 67,
                    'location' => NULL,
                    'address' => 'Jl Mawar',
                    'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                    'image' => 'storage/image/guideline/15934572890.jpeg,storage/image/guideline/15934572891.jpeg,storage/image/guideline/15934572892.jpeg,storage/image/guideline/15934572893.jpeg,storage/image/guideline/15934572904.jpeg,storage/image/guideline/15934572905.jpeg,storage/image/guideline/15934572906.jpeg',
                    'main_image' => 'storage/image/guideline/15934572890.jpeg',
                    'created_at' => '2020-06-29 19:01:30',
                    'updated_at' => '2020-06-29 19:01:30',
                ),
            7 =>
                array (
                    'id' => 8,
                    'agent' => 16,
                    'category' => 'Kos',
                    'isSell' => 0,
                    'isRent' => 0,
                    'name' => 'Kos  Cemara',
                    'bath_room' => 3,
                    'bed_room' => 4,
                    'stories' => 2,
                    'land_area' => 10,
                    'building_area' => 46,
                    'location' => NULL,
                    'address' => 'Jl Melati',
                    'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                    'image' => 'storage/image/guideline/15934574130.jpeg,storage/image/guideline/15934574131.jpeg,storage/image/guideline/15934574132.jpeg,storage/image/guideline/15934574133.jpeg,storage/image/guideline/15934574134.jpeg',
                    'main_image' => 'storage/image/guideline/15934574130.jpeg',
                    'created_at' => '2020-06-29 19:03:33',
                    'updated_at' => '2020-06-29 19:03:33',
                ),
            8 =>
                array (
                    'id' => 9,
                    'agent' => 16,
                    'category' => 'Kontrakan',
                    'isSell' => 0,
                    'isRent' => 0,
                    'name' => 'Perumahan Syariah',
                    'bath_room' => 1,
                    'bed_room' => 2,
                    'stories' => 1,
                    'land_area' => 5,
                    'building_area' => 35,
                    'location' => NULL,
                    'address' => 'Jl SBY',
                    'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                    'image' => 'storage/image/guideline/15934574970.jpeg,storage/image/guideline/15934574971.jpeg,storage/image/guideline/15934574972.jpeg,storage/image/guideline/15934574973.jpeg,storage/image/guideline/15934574974.jpeg',
                    'main_image' => 'storage/image/guideline/15934574970.jpeg',
                    'created_at' => '2020-06-29 19:04:57',
                    'updated_at' => '2020-06-29 19:04:57',
                ),
            9 =>
                array (
                    'id' => 10,
                    'agent' => 5,
                    'category' => 'Rumah',
                    'isSell' => 0,
                    'isRent' => 0,
                    'name' => 'Perumahan Indah',
                    'bath_room' => 2,
                    'bed_room' => 3,
                    'stories' => 1,
                    'land_area' => 10,
                    'building_area' => 40,
                    'location' => NULL,
                    'address' => 'Jl Sunan Kalaga',
                    'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                    'image' => 'storage/image/guideline/15934576120.webp,storage/image/guideline/15934576121.jpeg,storage/image/guideline/15934576122.jpeg,storage/image/guideline/15934576123.jpeg',
                    'main_image' => 'storage/image/guideline/15934576120.webp',
                    'created_at' => '2020-06-29 19:06:52',
                    'updated_at' => '2020-06-29 19:06:52',
                ),
            10 =>
                array (
                    'id' => 11,
                    'agent' => 5,
                    'category' => 'Kontrakan',
                    'isSell' => 0,
                    'isRent' => 0,
                    'name' => 'Perumahan Green',
                    'bath_room' => 1,
                    'bed_room' => 3,
                    'stories' => 2,
                    'land_area' => 5,
                    'building_area' => 45,
                    'location' => NULL,
                    'address' => 'Jl sunan',
                    'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                    'image' => 'storage/image/guideline/15934577320.webp,storage/image/guideline/15934577321.jpeg,storage/image/guideline/15934577322.jpeg,storage/image/guideline/15934577323.jpeg',
                    'main_image' => 'storage/image/guideline/15934577320.webp',
                    'created_at' => '2020-06-29 19:08:52',
                    'updated_at' => '2020-06-29 19:08:52',
                ),
            11 =>
                array (
                    'id' => 12,
                    'agent' => 4,
                    'category' => 'Rumah',
                    'isSell' => 0,
                    'isRent' => 0,
                    'name' => 'Perumahan Permai',
                    'bath_room' => 2,
                    'bed_room' => 2,
                    'stories' => 1,
                    'land_area' => 10,
                    'building_area' => 35,
                    'location' => NULL,
                    'address' => 'jl Gajayana',
                    'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                    'image' => 'storage/image/guideline/15934579360.webp,storage/image/guideline/15934579361.jpeg,storage/image/guideline/15934579362.jpeg,storage/image/guideline/15934579363.jpeg',
                    'main_image' => 'storage/image/guideline/15934579360.webp',
                    'created_at' => '2020-06-29 19:12:16',
                    'updated_at' => '2020-06-29 19:12:16',
                ),
        ));


    }
}
